# Nginx base image
FROM nginx:alpine

# Copy the Nginx configuration file
COPY ./docker/nginx_config/nginx.conf /etc/nginx/conf.d/

# NOTE: You need a directory called certificates with the correct certificates: certificate.crt, private.key, ca_bundle.crt

# Copy the SSL certificates
COPY ./certificates/certificate.crt /etc/nginx/ssl/certificate.crt
COPY ./certificates/private.key /etc/nginx/ssl/private.key
COPY ./certificates/ca_bundle.crt /etc/nginx/ssl/ca_bundle.crt

# Expose port 443 for SSL
EXPOSE 443

# Default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
